before_script:  
 - set ANDROID_SDK_ROOT = "D:\Android\sdk"

stages:
  - test
  - build

test:android:
  stage: test
  script:
    - cd android
    - ./gradlew app:assembleDebug 

build:apk:
  stage: build
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk

build:bundle:
  stage: build
  script:
    - flutter build appbundle
  artifacts:
    paths:
      - build/app/outputs/bundle

test:flutter:
  stage: test
  script:
    - flutter test
